### PR TITLE
TalkJs lib broke Firebase lib on iOS (fixed)

### PR DESCRIPTION
**Pull request by zSoNz**
Fix for this issue

https://github.com/talkjs/talkjs-flutter/issues/22

### CODE REVIEW

**Comment by vickz84259** [comment]
In order to be able to accept any PR and merge it, we require that every contributor has signed a CLA beforehand.
Please sign either the Individual or the Corporate CLA that you find in this repository, and email it to [legal@talkjs.com](mailto:legal@talkjs.com)

**Comment by vickz84259** [comment]
In the mean time, I'll test out your changes just to ensure there aren't any unexpected side effects with this version bump

**Comment by zSoNz** [comment]
> In order to be able to accept any PR and merge it, we require that every contributor has signed a CLA beforehand.
> Please sign either the Individual or the Corporate CLA that you find in this repository, and email it to [legal@talkjs.com](mailto:legal@talkjs.com)

Sure, will do it in few hours.

> In the mean time, I'll test out your changes just to ensure there aren't any unexpected side effects with this version bump

Sure. Thank you mate

**Comment by zSoNz** [comment]
> 

😳

Screenshot 2023-01-13 at 16 32 24

**Comment by eteeselink** [comment]
Hi Bogdan, can you try sending it to admin@talkjs.com instead? We'll investigate what's going on meanwhile. Thanks!!

**Comment by zSoNz** [comment]
@eteeselink , hey!

Just sended email with agreement for you.

**Comment by zSoNz** [comment]
@eteeselink @vickz84259 

bump

**Pull request merged**
